### PR TITLE
Update README.md, serverless configuration.

### PR DESCRIPTION
**Pull request by dwebpoint**
All tasks has been successfuly done

- Manual deployment has been explored and successfully done
- Serverless and serverless-finch with serverless-single-page-app-plugin were configured and automated deployment were successfuly done
- Links to [CloudFront](https://d1hr1524t5pseq.cloudfront.net/) and [S3-website retuning 403 Forbidden](https://aws-shop-react-redux-cloudfront-auto-provisioning.s3.amazonaws.com/index.html/) were provided in the README.md file

### CODE REVIEW

**Comment by yrypka** [comment]
@kitminsk Haven't you had issues with `serverless-single-page-app-plugin`? I can't see how you have enabled the plugin in .serverless_plugins directory.

**Comment by dwebpoint** [comment]
@yrypka Thanks for review. Fixed

**Review by yrypka — APPROVED** [review]
Approved

**Comment by DimDev** [comment]
👍

**Pull request merged**
